project_name: my_ml_app

seed: 42

device: "cuda"
workdir: "path/to/work/dir"
reference_wav: "path/to/reference"
sample_rate: 24000

asr:
  model_type: large
  save_results: false

tts:
  device: cpu
  checkpoint: null
  language: ru
  speed: 1.2
  length_penalty: 1
  repetition_penalty: 10.0
  temperature: 0.3
  cutoff: null

mt:
  model_name: Helsinki-NLP/opus-mt-en-ru

